
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    llama2-70b-wholemod-0-llama2-70b-whole:
        namespace: dasheng
        lang: python3-http
        handler: ./llama2-70b-wholemod-0
        image: k.harbor.siat.ac.cn/openfaas/cdgp-llama2-70b-wholemod-0-llama2-70b-whole:2.8.1.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 14000m
            memory: 64Gi
        environment:
            read_timeout: "2.0s"
            write_timeout: "2.0s"
            exec_timeout: "2.0s"
            debug: "false"
            infer_device: "cuda"
    
    llama2-70b-wholemod-1-llama2-70b-whole:
        namespace: dasheng
        lang: python3-http
        handler: ./llama2-70b-wholemod-1
        image: k.harbor.siat.ac.cn/openfaas/cdgp-llama2-70b-wholemod-1-llama2-70b-whole:2.8.1.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 13000m
            memory: 64Gi
        environment:
            read_timeout: "4.0s"
            write_timeout: "4.0s"
            exec_timeout: "4.0s"
            debug: "false"
            infer_device: "cuda"
    
    llama2-70b-wholemod-3-llama2-70b-whole:
        namespace: dasheng
        lang: python3-http
        handler: ./llama2-70b-wholemod-3
        image: k.harbor.siat.ac.cn/openfaas/cdgp-llama2-70b-wholemod-3-llama2-70b-whole:2.8.1.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 13000m
            memory: 64Gi
        environment:
            read_timeout: "6.0s"
            write_timeout: "6.0s"
            exec_timeout: "6.0s"
            debug: "false"
            infer_device: "cuda"
    
    llama2-70b-wholemod-2-llama2-70b-whole:
        namespace: dasheng
        lang: python3-http
        handler: ./llama2-70b-wholemod-2
        image: k.harbor.siat.ac.cn/openfaas/cdgp-llama2-70b-wholemod-2-llama2-70b-whole:2.8.1.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 13000m
            memory: 64Gi
        environment:
            read_timeout: "8.0s"
            write_timeout: "8.0s"
            exec_timeout: "8.0s"
            debug: "false"
            infer_device: "cuda"
    
    llama2-70b-wholemod-4-llama2-70b-whole:
        namespace: dasheng
        lang: python3-http
        handler: ./llama2-70b-wholemod-4
        image: k.harbor.siat.ac.cn/openfaas/cdgp-llama2-70b-wholemod-4-llama2-70b-whole:2.8.1.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 13000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    