
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    bert-21b-submod-20-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-20
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-20-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "0.48s"
            write_timeout: "0.48s"
            exec_timeout: "0.48s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-19-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-19
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-19-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "0.95s"
            write_timeout: "0.95s"
            exec_timeout: "0.95s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-18-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-18
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-18-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "1.43s"
            write_timeout: "1.43s"
            exec_timeout: "1.43s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-17-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-17
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-17-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "1.9s"
            write_timeout: "1.9s"
            exec_timeout: "1.9s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-16-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-16
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-16-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "2.38s"
            write_timeout: "2.38s"
            exec_timeout: "2.38s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-15-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-15
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-15-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "2.86s"
            write_timeout: "2.86s"
            exec_timeout: "2.86s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-14-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-14
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-14-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "3.33s"
            write_timeout: "3.33s"
            exec_timeout: "3.33s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-13-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-13
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-13-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "3.81s"
            write_timeout: "3.81s"
            exec_timeout: "3.81s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-12-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-12
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-12-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "4.29s"
            write_timeout: "4.29s"
            exec_timeout: "4.29s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-11-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-11
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-11-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "4.76s"
            write_timeout: "4.76s"
            exec_timeout: "4.76s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-10-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-10
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-10-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "5.24s"
            write_timeout: "5.24s"
            exec_timeout: "5.24s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-9-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-9
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-9-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "5.71s"
            write_timeout: "5.71s"
            exec_timeout: "5.71s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-8-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-8
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-8-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "6.19s"
            write_timeout: "6.19s"
            exec_timeout: "6.19s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-7-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-7
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-7-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "6.67s"
            write_timeout: "6.67s"
            exec_timeout: "6.67s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-6-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-6
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-6-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "7.14s"
            write_timeout: "7.14s"
            exec_timeout: "7.14s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-5-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-5
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-5-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "7.62s"
            write_timeout: "7.62s"
            exec_timeout: "7.62s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-4-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-4
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-4-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "8.1s"
            write_timeout: "8.1s"
            exec_timeout: "8.1s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-3-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-3
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-3-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "8.57s"
            write_timeout: "8.57s"
            exec_timeout: "8.57s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-2-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-2
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-2-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "9.05s"
            write_timeout: "9.05s"
            exec_timeout: "9.05s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-1-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-1
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-1-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "9.52s"
            write_timeout: "9.52s"
            exec_timeout: "9.52s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-0-me-21:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-0
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-0-me-21:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 1000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    