
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    opt-66b-submod-10-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-10
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-10-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "0.91s"
            write_timeout: "0.91s"
            exec_timeout: "0.91s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-9-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-9
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-9-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "1.82s"
            write_timeout: "1.82s"
            exec_timeout: "1.82s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-8-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-8
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-8-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "2.73s"
            write_timeout: "2.73s"
            exec_timeout: "2.73s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-7-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-7
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-7-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "3.64s"
            write_timeout: "3.64s"
            exec_timeout: "3.64s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-6-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-6
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-6-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "4.55s"
            write_timeout: "4.55s"
            exec_timeout: "4.55s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-5-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-5
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-5-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "5.45s"
            write_timeout: "5.45s"
            exec_timeout: "5.45s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-4-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-4
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-4-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "6.36s"
            write_timeout: "6.36s"
            exec_timeout: "6.36s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-3-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-3
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-3-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "7.27s"
            write_timeout: "7.27s"
            exec_timeout: "7.27s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-2-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-2
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-2-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "8.18s"
            write_timeout: "8.18s"
            exec_timeout: "8.18s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-1-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-1
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-1-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 6000m
            memory: 64Gi
        environment:
            read_timeout: "9.09s"
            write_timeout: "9.09s"
            exec_timeout: "9.09s"
            debug: "false"
            infer_device: "cuda"
    
    opt-66b-submod-0-me-11:
        namespace: cdgp
        lang: python3-http
        handler: ./opt-66b-submod-0
        image: k.harbor.siat.ac.cn/openfaas/cdgp-opt-66b-submod-0-me-11:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 5000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    