
version: 1.0
provider:
    name: openfaas
    gateway: http://serverless.siat.ac.cn:31112

functions:
    
    bert-21b-submod-9-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-9
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-9-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "1.0s"
            write_timeout: "1.0s"
            exec_timeout: "1.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-8-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-8
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-8-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "2.0s"
            write_timeout: "2.0s"
            exec_timeout: "2.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-7-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-7
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-7-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "3.0s"
            write_timeout: "3.0s"
            exec_timeout: "3.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-6-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-6
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-6-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "4.0s"
            write_timeout: "4.0s"
            exec_timeout: "4.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-5-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-5
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-5-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "5.0s"
            write_timeout: "5.0s"
            exec_timeout: "5.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-4-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-4
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-4-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "6.0s"
            write_timeout: "6.0s"
            exec_timeout: "6.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-3-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-3
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-3-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "7.0s"
            write_timeout: "7.0s"
            exec_timeout: "7.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-2-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-2
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-2-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "8.0s"
            write_timeout: "8.0s"
            exec_timeout: "8.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-1-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-1
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-1-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 2000m
            memory: 64Gi
        environment:
            read_timeout: "9.0s"
            write_timeout: "9.0s"
            exec_timeout: "9.0s"
            debug: "false"
            infer_device: "cuda"
    
    bert-21b-submod-0-latency-10:
        namespace: cdgp
        lang: python3-http
        handler: ./bert-21b-submod-0
        image: k.harbor.siat.ac.cn/openfaas/cdgp-bert-21b-submod-0-latency-10:2.8.2.dasheng
        requests:
            cpu: 1000m
            memory: 8Gi
        limits:
            cpu: 3000m
            memory: 64Gi
        environment:
            read_timeout: "10.0s"
            write_timeout: "10.0s"
            exec_timeout: "10.0s"
            debug: "false"
            infer_device: "cuda"
    